version: "3.1"

services:   

    nginx:
        container_name: nginx_proxy
        build: ./nginx
        restart: always
        ports:
          - 80:80
        depends_on:
          - api
    
    api:
        container_name: api_node
        build: ./api
        restart: always
        #volumes: 
        #    - ./api:/app
        depends_on: 
            - mysqld
        ports: 
            - 3000:3000    

    mysqld:
        build: ./mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        ports: 
            - 8081:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1075321220Pabl@
            MYSQL_USER: peescobar
            MYSQL_PASSWORD: 1075321220Pabl@
            MYSQL_DATABASE: personas
            TZ: America/Bogota

# Los volumenes se encuentran ubicados en la ruta
# /var/lib/docker/volumes/*
volumes:
    db-data:
